### ISSUE TITLE
Name issue

### ISSUE THREAD

**Issue by intrnl** [thatguywiththatname/BetterDiscord#1]
Not to trying to be condescending, but the name should be changed to avoid miscommunication and also preferably avoiding misunderstanding as well with the already existing [Better](https://github.com/Jiiks/BetterDiscordApp)[Discord](https://github.com/rauenzi/BetterDiscordApp)[.](https://github.com/JsSucks/BetterDiscordApp)

**Comment by thatguywiththatname** [comment]
I mean, i'm not planning on "releasing" this, it's just a personal project. If you search "Better Discord" on Github or Google this project isn't going to come up, to be honest i'm not sure how you found this in the first place lol. I can change it if you really think I should, but I don't see any point.
